#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.gofashion.gofashionspringcloudordersdetails.entity
  mapperLocations: classpath:mapper/*.xml
server:
  port: 8081
---

#开发配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/gofashion
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
# 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


---

spring:
 redis:
#数据库索引
   database: 0
   host: 127.0.0.1
   port: 6379
   jedis:
    pool:
#最大连接数
      max-active: 8
 #最大空闲
      max-idle: 8
#最小空闲
      min-idle: 0
---
#线程池配置
spring:
  task:
    pool:
      corePoolSize : 4
      maxPoolSize : 8
      keepAliveSeconds : 60
      queueCapacity : 20