#默认使用配置
spring:
  profiles:
    active: dev
---
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.gofashion.gofashionspringcloudordersdetails.entity
  mapperLocations: classpath:mapper/*.xml
server:
  port: 7001

spring:
  application:
    name: gofashion-cloud-orders-producer
  zipkin:
    base-url: http://116.62.167.249:6601
  sleuth:
    sampler:
      percentage: 1.0

  rabbitmq:
    host: 47.100.246.114
    port: 5672
    username: fashion
    password: fashion
    virtual-host: /goFashion
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
  redis:
#数据库索引
   database: 0
   host: 127.0.0.1
   port: 6379
   jedis:
    pool:
#最大连接数
      max-active: 8
 #最大空闲
      max-idle: 8
#最小空闲
      min-idle: 0

#开发配置
  datasource:
    url: jdbc:mysql://localhost:3306/gofashion
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
# 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


eureka:
  client:
    service-url:
      defaultZone: http://47.100.246.114:6001/eureka/
  #instance:

    #prefer-ip-address: true
logging:
    level: info





