server:
  port: 8001

spring:
  application:
    name: gofashion-cloud-orders-consumer
  zipkin:
    base-url: http://116.62.167.249:6601
    #日志追踪系统  追踪服务的的端口
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: 47.100.246.114
    port: 5672
    username: fashion
    password: fashion
    virtual-host: /goFashion
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
eureka:
  client:
    service-url:
      defaultZone: http://47.100.246.114:6001/eureka/

  #instance:
    #instance-id: loginandergister
    #prefer-ip-address: true
feign:
  hystrix:
    enabled: true
logging:
    level: info